site_name: LLM Chatbot for messengers
site_description: Time bound llm chatbot for various messengers like Kakaotalk, slack, etc.
site_author: sad-zero
copyright: MIT
repo_url: https://github.com/sad-zero/llm-chatbot-for-messengers
nav:
  - Home: index.md
  - Design:
    - Current: design/current.md
    - Future: design/future.md
  - About:
    - License: about/license.md
theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - python
plugins:
  - search
  - mermaid2
