-- Messenger Infos
CREATE SCHEMA CORE;

CREATE TABLE CORE.MESSENGERS (
    MESSENGER_SEQ SERIAL NOT NULL,
    MESSENGER_NAME CHARACTER VARYING NOT NULL UNIQUE,
    CONSTRAINT MESSENGER_PK PRIMARY KEY (MESSENGER_SEQ)
);

-- User Infos
CREATE TABLE CORE.USERS (
    USER_SEQ SERIAL NOT NULL,
    MESSENGER_SEQ INTEGER NOT NULL,
    USER_ID CHARACTER VARYING NOT NULL,
    USER_NAME CHARACTER VARYING, -- Username can be absent
    CONSTRAINT USERS_PK PRIMARY KEY (USER_SEQ),
    CONSTRAINT USERS_MESSENGERS_FK FOREIGN KEY (
        MESSENGER_SEQ
    ) REFERENCES CORE.MESSENGERS (MESSENGER_SEQ)
);
CREATE UNIQUE INDEX USERS_IDX01 ON CORE.USERS USING BTREE (
    MESSENGER_SEQ, USER_ID
);

-- Agent Infos
CREATE TABLE CORE.AGENTS (
    AGENT_SEQ SERIAL NOT NULL,
    AGENT_NAME CHARACTER VARYING NOT NULL UNIQUE,
    CONSTRAINT AGENTS_PK PRIMARY KEY (AGENT_SEQ)
);

-- Langgraph memories
-- @see https://pypi.org/project/langgraph-checkpoint-postgres/

CREATE TABLE PUBLIC.CHECKPOINTS (
    THREAD_ID CHARACTER VARYING NOT NULL, -- User in messengers
    CHECKPOINT_NS CHARACTER VARYING NOT NULL DEFAULT ''::TEXT, -- Topics
    CHECKPOINT_ID CHARACTER VARYING NOT NULL, -- Current chat Id
    PARENT_CHECKPOINT_ID CHARACTER VARYING, -- Previous chat Id
    "TYPE" CHARACTER VARYING,
    "CHECKPOINT" JSONB NOT NULL,
    METADATA JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT CHECKPOINTS_PK PRIMARY KEY (
        THREAD_ID, CHECKPOINT_NS, CHECKPOINT_ID
    )
);

CREATE TABLE PUBLIC.CHECKPOINT_BLOBS (
    THREAD_ID CHARACTER VARYING NOT NULL,
    CHECKPOINT_NS CHARACTER VARYING NOT NULL DEFAULT ''::TEXT,
    CHANNEL CHARACTER VARYING NOT NULL,
    "VERSION" CHARACTER VARYING NOT NULL,
    "TYPE" CHARACTER VARYING NOT NULL,
    "BLOB" BYTEA,
    CONSTRAINT CHECKPOINT_BLOBS_PK PRIMARY KEY (
        THREAD_ID, CHECKPOINT_NS, CHANNEL, "VERSION"
    )
);

CREATE TABLE PUBLIC.CHECKPOINT_MIGRATIONS (
    V INTEGER NOT NULL,
    CONSTRAINT CHECKPOINT_MIGRATIONS_PK PRIMARY KEY (V)
);

CREATE TABLE PUBLIC.CHECKPOINT_WRITES (
    THREAD_ID CHARACTER VARYING NOT NULL,
    CHECKPOINT_NS CHARACTER VARYING NOT NULL DEFAULT ''::TEXT,
    CHECKPOINT_ID CHARACTER VARYING NOT NULL,
    TASK_ID CHARACTER VARYING NOT NULL,
    IDX INTEGER NOT NULL,
    CHANNEL CHARACTER VARYING NOT NULL,
    "TYPE" CHARACTER VARYING NOT NULL,
    "BLOB" BYTEA NOT NULL,
    CONSTRAINT CHECKPOINT_WRITES_PK PRIMARY KEY (
        THREAD_ID, CHECKPOINT_NS, CHECKPOINT_ID, TASK_ID, IDX
    )
);
