name: CD
on:
  push:
    branches:
      - main
      - develop
      - feat/upload-to-acr
env:
  IMAGE_NAME: llm-chatbot-for-messengers
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.2.2
        - name: 'Login via Azure CLI'
          uses: azure/login@v2.2.0
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v2
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:test .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:test
