name: CD
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
env:
  IMAGE_NAME: llm-chatbot-for-messengers
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion == 'success' && (github.ref_name == 'main' || github.ref_name == 'develop')
        steps:
        - uses: actions/checkout@v4.2.2
        - name: 'Login via Azure CLI'
          uses: azure/login@v2.2.0
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v2
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
