name: CI
on:
    push:
        branches:
            - main
            - develop
            - ci/write-workflow
    pull_request:
        branches:
            - main
            - develop
jobs:
    style:
        runs-on: ubuntu-latest
        steps:
            - uses: Actions/checkout@v4.2.2
            - name: Setup environments
              run: |
                sudo apt update
                sudo apt install pipx -y
                pipx ensurepath
                pipx install hatch
            - name: Check style
              run: |
                hatch run types:check
                hatch fmt
            - name: Sync style
              run: |
                is_changed=$(git status | grep "Changes not staged for commit") || true
                if [ -n "$is_changed" ]; then
                    echo "Sync style"
                    git config user.name "bot"
                    git config user.email "bot@love.you"
                    git add .
                    git commit -m "Sync style"
                    git push origin ${{ github.ref_name}}
                    
                else
                    echo "Already sync style"
                fi
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: Actions/checkout@v4.2.2
            - name: Setup environments
              run: |
                sudo apt update
                sudo apt install pipx -y
                pipx ensurepath
                pipx install hatch
            - name: Check tests
              run: |
                hatch test -c
