name: CI
on:
    push:
        branches:
            - main
            - develop
            - ci/write-workflow
    pull_request:
        branches:
            - main
            - develop
jobs:
    style:
        runs-on: ubuntu-latest
        steps:
            - uses: Actions/checkout@v4.2.2
            - name: Setup environments
              run: |
                apt update
                apt install pipx -y
                pipx ensurepath
                pipx install hatch
            - name: Check style
              run: |
                hatch fmt
                hatch run types:check
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: Actions/checkout@v4.2.2
            - name: Setup environments
              run: |
                apt update
                apt install pipx -y
                pipx ensurepath
                pipx install hatch
            - name: Check tests
              run: |
                hatch test -c
